FROM ubuntu:latest

RUN apt update

RUN apt install -y git

RUN apt install -y curl

RUN git clone https://github.com/ESoapW/fibonacci_project.git

RUN cd fibonacci_project/project

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

EXPOSE 3000:3000